# Generated by Django 6.0.5 on 2026-06-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='accommodation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='excluded',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
