# Generated by Django 6.0.5 on 2026-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_accommodation_tour_equipment_tour_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='guide_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
